### PR TITLE
Add openai env options; Add example script

### PR DESCRIPTION
**Pull request by yhyu13**
1, Allow users to quickly adjust API key, base url, model using env variables. For example, startup different instances using docker with different .env, etc
2, Add example script from readme to repo
3, Add ReAct prompts as an option
4, Add chat completion api/response support for gpt4/chagpt, and rate limiter exception handle as well

### CODE REVIEW

**Comment by yhyu13** [comment]
Let me know if you have any question about this pr

**Comment by kyegomez** [comment]
Hey it looks great but I published an all-new release and it might conflict with some of the commits you've made, I added in additional params to the solve method of treeofthoughts

**Comment by yhyu13** [comment]
> Thanks for contributing blush
> 
> Hey it looks great but I published an all-new release and it might conflict with some of the commits you've made, I added in additional params to the solve method of treeofthoughts can you double check and see if there are any conflicts and then submit with all of your changes?

Sure thing.

**Comment by yhyu13** [comment]
Added chat completion support for https://github.com/kyegomez/tree-of-thoughts/issues/7

**Review by kyegomez — CHANGES_REQUESTED** [review]
Thanks looks great, can you provide new examples for the readme.md?

**Pull request merged**
